#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

################################################################################
# . ${R}etc/init.d/rc.vtol_defaults
#
# VTOL default parameters.
#
# NOTE: Script variables are declared/initialized/unset in the rcS script.
#

set VEHICLE_TYPE vtol

# MAV_TYPE_VTOL_FIXEDROTOR 22
param set-default MAV_TYPE 22

# there is a 2.5 factor applied on COM_POS_FS_EPH if for invalidation
param set-default COM_POS_FS_EPH 50

param set-default COM_POS_LOW_EPH 50

param set-default MIS_TAKEOFF_ALT 20
param set-default MIS_YAW_TMT 10

param set-default EKF2_ARSP_THR 10
param set-default EKF2_FUSE_BETA 1

param set-default HTE_VXY_THR 2

param set-default MIS_TKO_LAND_REQ 2

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_VEL_MANUAL 5
param set-default MPC_XY_ERR_MAX 5
param set-default MPC_XY_VEL_MAX 8
param set-default MPC_JERK_MAX 4.5
param set-default MPC_YAW_MODE 4

# reduce aggressiveness around roll and yaw axis,
# as VTOLs usually have high intertia and lot af drag due to wings
param set-default MC_ROLL_P 5
param set-default MC_ROLLRATE_MAX 120
param set-default MC_YAW_P 2
param set-default MC_YAWRATE_MAX 120
param set-default MPC_MAN_Y_MAX 90

param set-default RTL_TYPE 1

param set-default SYS_HAS_NUM_ASPD 1 # by default require an airspeed sensor

param set-default WV_EN 1

################################################################################

# Original airframe

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=quadtailsitter}

param set-default SIM_GZ_EN 1 # Gazebo bridge

param set-default MAV_TYPE 20

param set-default CA_AIRFRAME 4

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.23
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.23
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.23
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.23
param set-default CA_ROTOR3_KM -0.05

param set-default CA_SV_CS_COUNT 0

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MIN4 10

param set-default SIM_GZ_EC_MAX1 1500
param set-default SIM_GZ_EC_MAX2 1500
param set-default SIM_GZ_EC_MAX3 1500
param set-default SIM_GZ_EC_MAX4 1500

param set-default FD_FAIL_R 70

param set-default FW_P_TC 0.6

param set-default FW_PR_I 0.3
param set-default FW_PR_P 0.5
param set-default FW_PSP_OFF 2
param set-default FW_RR_FF 0.1
param set-default FW_RR_I 0.1
param set-default FW_RR_P 0.2
param set-default FW_YR_FF 0 # make yaw rate controller very weak, only keep default P
param set-default FW_YR_I 0
param set-default FW_THR_TRIM 0.35
param set-default FW_THR_MAX 0.8
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 6
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 3
param set-default FW_T_SINK_MIN 1.6
param set-default FW_AIRSPD_STALL 10
param set-default FW_AIRSPD_MIN 14
param set-default FW_AIRSPD_TRIM 18
param set-default FW_AIRSPD_MAX 22

param set-default MC_AIRMODE 2
param set-default MAN_ARM_GESTURE 0 # required for yaw airmode
param set-default MC_ROLL_P 3
param set-default MC_PITCH_P 3
param set-default MC_ROLLRATE_P 0.3
param set-default MC_PITCHRATE_P 0.3

param set-default VT_ARSP_TRANS 15
param set-default VT_B_TRANS_DUR 5
param set-default VT_FW_DIFTHR_EN 7
param set-default VT_FW_DIFTHR_S_Y 1
param set-default VT_F_TRANS_DUR 1.5
param set-default VT_TYPE 0

param set-default WV_EN 0

param set-default EKF2_FUSE_BETA 0

################################################################################

# AAS Custom

# Simulated sensors
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default COM_RCL_EXCEPT 7 # Disable RC loss action
param set-default UXRCE_DDS_SYNCT 0 # This lets PX4 SITL keep using Gazebo simulation time
param set-default MPC_XY_CRUISE 3.0 # Limit the VTOL's multicopter mode position controller speed

# Configure "Hold" behaviour
param set-default NAV_LOITER_RAD 500 # Default radius for Hold mode and MAV_CMD_DO_REPOSITION
param set-default VTO_LOITER_ALT 150 # Altitude relative to home at which vehicle will loiter in Hold mode

# Configure "Offboard" failsafe behaviour
param set-default COM_QC_ACT -1 # No quadchute, FUN BUT DO NOT USE IN REAL LIFE
param set-default COM_OBL_RC_ACT 5 # Force hold mode when falling out of offboard
param set-default COM_OF_LOSS_T 1.0 # Timeout for the offboard failsafe to kick in
param set-default NAV_RCL_ACT 1 # RC loss failsafe mode: hold mode
param set-default COM_RC_OVERRIDE 1 # Enable RC stick override of auto (0) and/or offboard modes (1)

# Increase timeouts/rates for faster-than-real-life simulation
param set-default COM_RC_LOSS_T 35
param set-default COM_DL_LOSS_T 300

param set-default FD_ESCS_EN 0 # Disable ESCs checks reporting
